apiVersion: v1
kind: Secret
metadata:
  name: mongo-wiki-secret
stringData:
  MONGO_CONNECTION_STRING: "mongodb+srv://maxitemis:JBU6JkJRNYN73bb@cluster0.x5da5.mongodb.net/?retryWrites=true&w=majority"
type: Opaque
